name: backup-notion
env:
  NOTION_BLOCK_ID: "'3c2614e58cf64399b5b561e873ef61e5, 26c9e464186648c38160ed5b8e5a3277'"
on:
  push:
  schedule:
    - cron: "0/5 * * * *" #
jobs:
  backup-notion:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
      - run: npm install
      - name: build script
        run: npm run build
        continue-on-error: true
      - run: npm run run-backup $NOTION_BLOCK_ID
      - name: backup as artifact
        uses: actions/upload-artifact@v3
        with: 
          name: notion-backup-zip
          path: backupZip