name: test-github-action
on:
  push:
  schedule:
    - cron: "55 5 * * *" # 北京时间 13:55
jobs:
  test_nodejs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
      - run: node -v
      - run: npm run test-action
