name: test-github-action
on:
  push:
  schedule:
    - cron: "0/5 * * * *" #
jobs:
  test_nodejs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
      - run: node -v
      - run: npm run build
      - run: npm run run-backup "3c2614e58cf64399b5b561e873ef61e5, 26c9e464186648c38160ed5b8e5a3277"
